name: Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install dependencies
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Type
        run: npm run check-types
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            COOKIE
            PASSWORD
        env:
          COOKIE: ${{ secrets.COOKIE }}
          PASSWORD: ${{ secrets.PASSWORD }}